@props(['name', 'weight' => 'regular'])
@php
    $icons = [
        'sparkle' => 'sparkle',
        'house' => 'house',
        'archive' => 'archive',
        'list' => 'list-checks',
        'crown' => 'crown',
        'note' => 'note-pencil',
        'gear' => 'gear',
        'search' => 'magnifying-glass',
        'sliders' => 'sliders-horizontal',
        'bell' => 'bell',
        'user' => 'user',
        'bookmark' => 'bookmark-simple',
        'star' => 'star',
        'chart' => 'chart-bar',
        'clock' => 'clock',
        'calendar' => 'calendar-blank',
        'chevron-right' => 'caret-right',
        'play'  => 'play',
        'check' => 'check',
        'trash' => 'trash',
        'x'              => 'x',
        'arrow-left'     => 'arrow-left',
        'refresh'        => 'arrows-clockwise',
        'video'          => 'video-camera',
        'warning'        => 'warning',
        'youtube'        => 'youtube-logo',
        'google'         => 'google-logo',
        'pencil'         => 'pencil-simple',
        'plus'           => 'plus',
        'heart'          => 'heart',
        'heart-fill'     => 'heart',
        'timer'          => 'timer',
        'external'       => 'arrow-square-out',
        'tag'            => 'tag',
        'spinner'        => 'spinner',
        'dots'           => 'dots-three',
        'link'           => 'link',
    ];
    $family = $weight === 'fill' ? 'ph-fill' : 'ph';
@endphp
<i {{ $attributes->merge(['class' => "$family ph-".($icons[$name] ?? $name).' icon']) }} aria-hidden="true"></i>
