services:
  app:
    build: .
    volumes:
      - .:/var/www
    depends_on:
      - db

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  queue:
    build: .
    command: php artisan queue:work --sleep=3 --tries=3 --backoff=60
    volumes:
      - .:/var/www
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: varchive
      POSTGRES_USER: varchive
      POSTGRES_PASSWORD: admin
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

